//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 211506358
//  @ File Name : StaticData.h
//  @ Date : 2017/9/29 ÐÇÆÚÎå
//  @ Author : 
//
//


#if !defined(_STATICDATA_H)
#define _STATICDATA_H


class StaticData {
public:
	StaticData sharedStaticData();
	void purge();
	int intValueForKey(std: :string Key);
	char stringValueFromKey(:string :key std);
	void float ValueFromKey(:string: key std);
	void booleanFromKey(:string: key std);
	cocos2d(): :CCPoint pointFromKey(:string: key std);
	cocos2d: :CCRect rectFromKey(:string :key std);
	cocos2d: :CCSize sizeFromKey(:string: key std);
protected:
	cocos2d: :CCDictionary _dictionary;
	std: :string _staticFileNmae;
	bool init();
private:
	void StaticData();
	StaticData();
};

#endif  //_STATICDATA_H
