//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 211506358
//  @ File Name : StaticData.cpp
//  @ Date : 2017/9/29 ÐÇÆÚÎå
//  @ Author : 
//
//


#include "StaticData.h"

StaticData StaticData::sharedStaticData() {

}

void StaticData::purge() {

}

int StaticData::intValueForKey(std: :string Key) {

}

char StaticData::stringValueFromKey(:string :key std) {

}

void StaticData::float ValueFromKey(:string: key std) {

}

void StaticData::booleanFromKey(:string: key std) {

}

cocos2d(): :CCPoint StaticData::pointFromKey(:string: key std) {

}

cocos2d: :CCRect StaticData::rectFromKey(:string :key std) {

}

cocos2d: :CCSize StaticData::sizeFromKey(:string: key std) {

}

bool StaticData::init() {

}

void StaticData::StaticData() {

}

StaticData::StaticData() {

}

